"""Locks in the ``_ProxyShim.__setattr__`` forwarding contract.

When ``generate_training_data.py`` was split into the
``backend/scripts/training/`` package (Wave 5 / gap-closure Phase 3),
each submodule received its own copy of the verbatim header constants
(``RISK_FREE_RATE``, ``MIN_IV``, ``CONTRACT_MULT``, ...).  That made
the bytecode regression byte-identical, but it broke a long-standing
test idiom::

    monkeypatch.setattr(generate_training_data, "RISK_FREE_RATE", 0.10)

After the split, the assignment landed on the *shim* module's
namespace and never reached any submodule's copy, so any function
inside (say) ``training.candidates`` continued to read its private
``RISK_FREE_RATE = 0.04``.  To preserve runtime semantics, the shim
generated by ``tools/split_monolith.py`` (when ``PROXY_SHIM = True``
in the manifest) installs a custom module subclass, ``_ProxyShim``,
whose ``__setattr__`` propagates every write to all submodules that
already have an attribute by that name -- see
``tools/split_monolith.py:163-179``.

This module exercises that contract directly, without depending on
any of the larger pipeline tests, so a future refactor that drops
the proxy (or breaks the propagation logic) is caught immediately.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))


@pytest.fixture(name="shim_and_subs")
def _shim_and_subs() -> tuple[object, list[object], str]:
    """Import the shim + its submodules and pick a constant present on all submodules.

    Returns ``(shim_module, [submodule, ...], attribute_name)``.

    The attribute is chosen by introspection so the test stays valid
    if the manifest is ever re-cut: we look for any UPPER_CASE name
    present on at least two submodules.  ``RISK_FREE_RATE`` is the
    expected pick today (lives in the verbatim header copied into all
    five submodules), but if it's removed in a future refactor the
    test will silently switch to the next eligible attribute rather
    than break.
    """
    import generate_training_data as shim
    from training import (
        bs_gex_spot,
        candidates,
        cli,
        io_loaders,
        labeling,
    )

    submodules = [bs_gex_spot, io_loaders, candidates, labeling, cli]

    # Find any upper-case attribute present on >=2 submodules so we
    # have a real propagation target to write to.
    candidate_names = [
        name
        for name in vars(submodules[0])
        if name.isupper()
        and not name.startswith("_")
        and sum(1 for m in submodules if hasattr(m, name)) >= 2
    ]
    assert candidate_names, (
        "No shared upper-case attribute found on training submodules -- "
        "the proxy-shim test needs at least one to verify forwarding."
    )
    return shim, submodules, candidate_names[0]


def test_proxy_shim_setattr_propagates_to_submodules(
    shim_and_subs: tuple[object, list[object], str],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Writing to the shim must reach every submodule that has the attribute.

    Steps:

    1. Snapshot the pre-test value on every submodule that has the
       attribute.
    2. Use ``monkeypatch.setattr`` on the *shim* with a sentinel value.
    3. Assert every submodule that originally had the attribute now
       returns the sentinel (-> proxy forwarding works).
    4. Assert the shim itself also returns the sentinel (-> base
       behaviour preserved).
    5. After the test, ``monkeypatch`` restores the shim attribute --
       confirm the restoration also propagates back to the submodules
       (otherwise subsequent tests would leak the sentinel).
    """
    shim, submodules, attr = shim_and_subs
    sentinel = object()

    holders = [m for m in submodules if hasattr(m, attr)]
    assert len(holders) >= 2, (
        f"Expected >=2 submodules to hold {attr!r}; the proxy can't "
        f"demonstrate forwarding behaviour with fewer."
    )
    pre_values = {m.__name__: getattr(m, attr) for m in holders}

    # The pivotal call: the test idiom we're trying to preserve.
    monkeypatch.setattr(shim, attr, sentinel)

    assert getattr(shim, attr) is sentinel, (
        "Shim itself didn't pick up the new value -- the _ProxyShim "
        "subclass may have been removed or its __setattr__ broken."
    )
    for m in holders:
        assert getattr(m, attr) is sentinel, (
            f"Proxy did not propagate {attr!r} to submodule "
            f"{m.__name__!r} (got {getattr(m, attr)!r})"
        )

    # Roll back manually to verify the proxy survives a normal setattr
    # too (monkeypatch teardown will re-set the shim, but if the
    # proxy is broken in either direction the leak surfaces here).
    for m, original in pre_values.items():
        # Touch the shim again (not the submodule) so the proxy has
        # to do the work: this is what monkeypatch's teardown does.
        setattr(shim, attr, original)
        assert getattr(shim, attr) == original
        for sub in holders:
            assert getattr(sub, attr) == original, (
                f"Proxy did not restore {attr!r} on {sub.__name__!r}"
            )
        break  # one round-trip is enough; the loop just guards typos.


def test_proxy_shim_subclass_is_installed() -> None:
    """The shim module's class must be a subclass of ``ModuleType`` named ``_ProxyShim``.

    A regression here typically means ``tools/split_monolith.py`` was
    re-run with ``PROXY_SHIM = False`` in the manifest, or somebody
    edited the generated shim by hand and dropped the
    ``_sys.modules[__name__].__class__ = _ProxyShim`` line.
    """
    import generate_training_data as shim

    cls = type(shim)
    assert cls.__name__ == "_ProxyShim", (
        f"Expected shim module class to be _ProxyShim; got {cls.__name__}. "
        f"The setattr-forwarding behaviour is gone."
    )
